name: PNPM-PR-Snyk-Check

on: 
  push:
    branches:
      - '*'
  
jobs:
  pnpm_snyk_check:
    runs-on: ubuntu-latest
    name: Snyk post processing
    steps:
      - uses: actions/checkout@v2
      - name: Snyk API pnpm scan
        id: pnpm-scan-api-tool
        uses: ./
        with:
          snykToken: ${{ secrets.SNYK_TOKEN }}
          pnpmLockfilePath: "./test/fixtures/pnpm_simple"
          snykOrganization: "playground"
          IncludeDev: "true"


