name: PNPM-PR-Snyk-Check

on:
  pull_request:
    branches:
      - fix/AddMonorepoSupportTest
      - master
  push:
    branches:
      - fix/AddMonorepoSupportTest
      - master
  workflow_dispatch:
  
jobs:
  pnpm_snyk_check:
    runs-on: ubuntu-latest
    name: Snyk post processing
    steps:
      - uses: actions/checkout@v2
      - name: Snyk API pnpm scan
        id: pnpm-scan-api-tool
        uses: ./
        with:
          snykToken: ${{ secrets.SNYK_TOKEN }}
          pnpmLockfilePath: "."
          snykOrganization: "playground"
          IncludeDev: "true"


